//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YUYITOS.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA
    {
        public BOLETA()
        {
            this.DETALLE_BOLETA = new HashSet<DETALLE_BOLETA>();
        }
    
        public int ID_BOLETA { get; set; }
        public int TOTAL_NETO { get; set; }
        public int CLIENTE_RUT { get; set; }
        public System.DateTime FECHA_BOLETA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<DETALLE_BOLETA> DETALLE_BOLETA { get; set; }
    }
}
