//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YUYITOS.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.BOLETA = new HashSet<BOLETA>();
            this.CLIENTE_FIADO = new HashSet<CLIENTE_FIADO>();
        }
    
        public int ID_CLIENTE { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<BOLETA> BOLETA { get; set; }
        public virtual ICollection<CLIENTE_FIADO> CLIENTE_FIADO { get; set; }
    }
}
