//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YUYITOS.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_FIADO
    {
        public CLIENTE_FIADO()
        {
            this.ABONO_FIADO = new HashSet<ABONO_FIADO>();
        }
    
        public decimal ID_CLIENTE_FIADO { get; set; }
        public string ESTADO { get; set; }
        public System.DateTime FECHA_CONVENIDA { get; set; }
        public int CLIENTE_ID_CLIENTE { get; set; }
        public int MONTO_TOTAL { get; set; }
        public int MONTO_PAGADO { get; set; }
        public int MONTO_ADEUDADO { get; set; }
        public short ESTADO_PAGADO { get; set; }
    
        public virtual ICollection<ABONO_FIADO> ABONO_FIADO { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
