//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YUYITOS.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_BOLETA
    {
        public int ID_DETALLE_BOLETA { get; set; }
        public int BOLETA_ID_BOLETA { get; set; }
        public int PRODUCTO_ID_PRODUCTO { get; set; }
    
        public virtual BOLETA BOLETA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
