//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YUYITOS.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_STOCK
    {
        public DETALLE_STOCK()
        {
            this.DETALLE_BOLETA = new HashSet<DETALLE_BOLETA>();
        }
    
        public int ID_DETALLE_STOCK { get; set; }
        public int CANT_DETALLE_STOCK { get; set; }
        public int CODIGO_BARRA { get; set; }
        public decimal STOCK_ID_STOCK { get; set; }
        public int PRODUCTO_PROVEEDOR_ID { get; set; }
    
        public virtual ICollection<DETALLE_BOLETA> DETALLE_BOLETA { get; set; }
        public virtual PRODUCTO_PROVEEDOR PRODUCTO_PROVEEDOR { get; set; }
        public virtual STOCK STOCK { get; set; }
    }
}
