//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YUYITOS.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN
    {
        public ORDEN()
        {
            this.DETALLE_ORDEN = new HashSet<DETALLE_ORDEN>();
            this.RECEPCION = new HashSet<RECEPCION>();
        }
    
        public decimal ID_ORDEN { get; set; }
        public decimal ID_USUARIO { get; set; }
        public System.DateTime CREADO_EN { get; set; }
        public decimal PROVEEDOR_ID_PROVEEDOR { get; set; }
        public short ESTADO_ORDEN { get; set; }
    
        public virtual ICollection<DETALLE_ORDEN> DETALLE_ORDEN { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual ICollection<RECEPCION> RECEPCION { get; set; }
    }
}
