//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YUYITOS.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_PROVEEDOR
    {
        public PRODUCTO_PROVEEDOR()
        {
            this.DETALLE_ORDEN = new HashSet<DETALLE_ORDEN>();
            this.DETALLE_STOCK = new HashSet<DETALLE_STOCK>();
        }
    
        public int ID_PRODUCTO_P { get; set; }
        public int PRODUCTO_ID { get; set; }
        public decimal PROVEEDOR_ID { get; set; }
        public int PRECIO_VENTA { get; set; }
    
        public virtual ICollection<DETALLE_ORDEN> DETALLE_ORDEN { get; set; }
        public virtual ICollection<DETALLE_STOCK> DETALLE_STOCK { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
