//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YUYITOS.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public PROVEEDOR()
        {
            this.ORDEN = new HashSet<ORDEN>();
            this.PRODUCTO_PROVEEDOR = new HashSet<PRODUCTO_PROVEEDOR>();
            this.RECEPCION = new HashSet<RECEPCION>();
        }
    
        public decimal ID_PROVEEDOR { get; set; }
        public string NOMBRE { get; set; }
        public int RUT { get; set; }
        public string DV { get; set; }
        public string EMAIL { get; set; }
        public int TELEFONO { get; set; }
        public string RUBRO { get; set; }
        public int CIUDAD_ID { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual ICollection<ORDEN> ORDEN { get; set; }
        public virtual ICollection<PRODUCTO_PROVEEDOR> PRODUCTO_PROVEEDOR { get; set; }
        public virtual ICollection<RECEPCION> RECEPCION { get; set; }
    }
}
