//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YUYITOS.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEPCION
    {
        public int ID_RECEPCION { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal STOCK_ID_STOCK { get; set; }
        public decimal PROVEEDOR_ID_PROVEEDOR { get; set; }
        public decimal ORDEN_ID_ORDEN { get; set; }
        public int DETALLE_RECEP_ID_D_RECEP { get; set; }
    
        public virtual ORDEN ORDEN { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual STOCK STOCK { get; set; }
    }
}
