//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YUYITOS.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEPCION
    {
        public RECEPCION()
        {
            this.DETALLE_RECEPCION = new HashSet<DETALLE_RECEPCION>();
        }
    
        public int ID_RECEPCION { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal PROVEEDOR_ID { get; set; }
        public decimal ORDEN_ID_ORDEN { get; set; }
    
        public virtual ICollection<DETALLE_RECEPCION> DETALLE_RECEPCION { get; set; }
        public virtual ORDEN ORDEN { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
