//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YUYITOS.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK
    {
        public STOCK()
        {
            this.DETALLE_RECEPCION = new HashSet<DETALLE_RECEPCION>();
            this.DETALLE_STOCK = new HashSet<DETALLE_STOCK>();
        }
    
        public decimal ID_STOCK { get; set; }
        public System.DateTime FECHA_VENCIMIENTO { get; set; }
    
        public virtual ICollection<DETALLE_RECEPCION> DETALLE_RECEPCION { get; set; }
        public virtual ICollection<DETALLE_STOCK> DETALLE_STOCK { get; set; }
    }
}
