//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YUYITOS.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABONO_FIADO
    {
        public int ID_ABONO { get; set; }
        public int CANTIDAD { get; set; }
        public decimal CLIENTE_FIADO_ID_CLIENTE_FIADO { get; set; }
    
        public virtual CLIENTE_FIADO CLIENTE_FIADO { get; set; }
    }
}
