//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YUYITOS.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.DETALLE_BOLETA = new HashSet<DETALLE_BOLETA>();
            this.DETALLE_ORDEN = new HashSet<DETALLE_ORDEN>();
            this.DETALLE_RECEPCION = new HashSet<DETALLE_RECEPCION>();
            this.DETALLE_STOCK = new HashSet<DETALLE_STOCK>();
            this.STOCK = new HashSet<STOCK>();
            this.DETALLE_ORDEN1 = new HashSet<DETALLE_ORDEN>();
        }
    
        public int ID_PRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal PRECIO { get; set; }
        public decimal TIPO_PRODUCTO_ID_TIPO_PRODUCTO { get; set; }
        public decimal FAMILIA_ID_FAMILIA { get; set; }
        public Nullable<decimal> TIPO_ALIMENTO_ID_TIPO_ALIMENTO { get; set; }
    
        public virtual ICollection<DETALLE_BOLETA> DETALLE_BOLETA { get; set; }
        public virtual ICollection<DETALLE_ORDEN> DETALLE_ORDEN { get; set; }
        public virtual ICollection<DETALLE_RECEPCION> DETALLE_RECEPCION { get; set; }
        public virtual ICollection<DETALLE_STOCK> DETALLE_STOCK { get; set; }
        public virtual FAMILIA FAMILIA { get; set; }
        public virtual TIPO_ALIMENTO TIPO_ALIMENTO { get; set; }
        public virtual TIPO_PRODUCTO TIPO_PRODUCTO { get; set; }
        public virtual ICollection<STOCK> STOCK { get; set; }
        public virtual ICollection<DETALLE_ORDEN> DETALLE_ORDEN1 { get; set; }
    }
}
